set-window-option -g mode-keys vi
set -g base-index 1
set -g pane-base-index 1
# setw -g history-limit 50000000
set-option -g status "on"

# nvim recommended settings
set-option -sg escape-time 10
set-option -g focus-events on
set-option -sa terminal-features ',xterm-256color:RGB'

set -g default-command "${SHELL}"

run-shell "powerline-daemon -q"
source $HOME/.local/pipx/venvs/powerline-status/lib/python3.14/site-packages/powerline/bindings/tmux/powerline.conf
